// Builds curation/PLATES.md — the drawing list for the specimen plates.
//
//   npm run plates:brief
//
// It invents nothing. Every specimen's subject is the `plant_analogue` already
// written into public/field-notes.txt, which turns out to have been an
// illustration brief all along: "Corms & bulbs (e.g. Crocus, Gladiolus)",
// "Pitcher plant seedling stage", "Dandelion & thistle achenes".
//
// Grouped by organ, because that is where the work actually collapses. An
// evolution line usually shares one organ across three stages — bulb, bud,
// bloom; pitcher seedling, trap, mature trap — and a plate showing one organ at
// three stages is an ordinary botanical plate rather than three drawings.
//
// The last section is the honest one: specimens whose analogue names no organ
// at all. Some are fine and simply need reading. Some — a possessed lawnmower,
// a machine, a type-swapping deity — have no botanical part to draw, and want a
// decision before a pencil rather than during.
import { readFile, writeFile, mkdir } from "node:fs/promises";

const NOTES = new URL("../public/field-notes.txt", import.meta.url);
const OUT = new URL("../curation/PLATES.md", import.meta.url);

// Order matters: a specimen lands in the first group it matches, so the more
// specific patterns come first.
const GROUPS = [
  ["Bulbs, corms and tubers", /bulb|corm|tuber|geophyte|storage root|rhizome/i],
  ["Pitchers and traps", /pitcher|trap|carnivor|flytrap|venus/i],
  ["Seeds, fruits and dispersal", /seed|achene|samara|acorn|pappus|burr|bur-|spore|cone|fruit|apple|berry|drupe|olive|cherry|pumpkin|gourd|nut/i],
  ["Flowers and inflorescences", /flower|bloom|anthesis|floral|rose|petal|orchid|pollen|nectar/i],
  ["Leaves and foliage", /leaf|leaves|foliage|frond|epidermis|cuticle|blade|needle/i],
  ["Wood, bark and structure", /wood|timber|trunk|lignif|bark|stem|cambium|thicket|sapling|tree/i],
  ["Fungi", /fung|mushroom|mycel|cordyceps|puffball|agaric|lichen/i],
  ["Roots and the soil", /root|soil|topsoil|rhizosphere|litter|detritus|mycorrhiz/i],
  ["Vines and climbers", /vine|liana|climb|bindweed|kudzu|tendril/i],
  ["Arid and succulent", /cactus|succulen|arid|desert|cam\b/i],
  ["Water and algae", /aquatic|water lil|wetland|emergent|algae|kelp|seaweed|holdfast|marine|crinoid/i],
  ["Grasses and ground cover", /grass|turf|sedge|moss|graz|ground cover/i],
];

function parse(text) {
  const lines = text.replace(/\r\n?/g, "\n").split("\n");
  const out = [];
  let cur = null;
  for (const line of lines) {
    if (line.startsWith("### END")) { if (cur) out.push(cur); cur = null; continue; }
    if (line.startsWith("### ")) {
      const name = line.slice(4).split("[")[0].trim();
      cur = name.startsWith("TEMPLATE") ? null : { name, analogue: "", concept: "" };
      continue;
    }
    if (!cur) continue;
    const m = /^(plant_analogue|genetic_concept):(.*)$/.exec(line);
    if (m) cur[m[1] === "plant_analogue" ? "analogue" : "concept"] = m[2].trim();
  }
  return out.filter((b) => b.analogue);
}

async function run() {
  const blocks = parse(await readFile(NOTES, "utf8"));

  const placed = new Map(GROUPS.map(([title]) => [title, []]));
  const unplaced = [];
  for (const b of blocks) {
    const group = GROUPS.find(([, re]) => re.test(b.analogue));
    if (group) placed.get(group[0]).push(b);
    else unplaced.push(b);
  }

  const rows = (list) => list
    .map((b) => `| ${b.name} | ${b.analogue} | ${b.concept} |`)
    .join("\n");

  const body = `# Specimen plates — the drawing list

Generated by \`npm run plates:brief\` from the \`plant_analogue\` field of every
block in \`public/field-notes.txt\`. Do not edit by hand; edit the field notes and
regenerate.

**${blocks.length} specimens**, grouped by the organ their analogue names. The
count that matters is not the row count — evolution lines share an organ across
stages, so a line is usually one subject drawn two or three times rather than
three separate drawings.

The brief for each is its own analogue. The third column is the concept the note
argues, which is what the drawing has to make visible.

${GROUPS.map(([title]) => {
  const list = placed.get(title);
  if (!list.length) return "";
  return `## ${title} — ${list.length}

| specimen | draw | so that it shows |
|---|---|---|
${rows(list)}
`;
}).filter(Boolean).join("\n")}
## No organ named — ${unplaced.length}

These name no plant part, and they are the ones to decide before drawing rather
than during. Several are fine on a second reading — a banana plant, cotton, an
olive — and simply describe the whole organism. A few genuinely have no
botanical part at all: a possessed lawnmower, a machine, a trait-swapping deity.
For those the field note usually already contains the answer. Rotom-Mow's note,
for instance, is about the lawn and why grass survives being cut, which is a
drawable subject even though the specimen is an appliance.

| specimen | analogue | concept |
|---|---|---|
${rows(unplaced)}
`;

  await mkdir(new URL("../curation/", import.meta.url), { recursive: true });
  await writeFile(OUT, body);
  console.log(`PLATES.md — ${blocks.length} specimens, ${GROUPS.filter(([t]) => placed.get(t).length).length} organ groups, ${unplaced.length} undecided`);
}

run();
